name: Main Build and Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # merge_group:
  #   types: ['checks_requested']

jobs:
  setup:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir and Phoenix
        uses: erlef/setup-beam@v1.16
        with:
          elixir-version: 1.15.7
          otp-version: 26.0
      - name: Install Backend Dependencies
        run: |
          cd api
          pwd
          mix deps.get
          mix test
      - name: Run Backend Tests
        run: |
          cd api
          pwd
          echo "Current directory: $PWD"
          mix test

  frontend-build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    # needs: setup

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          # cache: "yarn"
      - name: Install Frontend Dependencies
        run: |
          cd front_time_manager
          pwd
          yarn
      - name: Test
        run: |
          echo "coucou"

  # backend-build:
  #   name: Build and Test Backend
  #   runs-on: ubuntu-latest
  #   needs: setup

  # - name: Run Backend Tests
  #   run: |
  #     cd api_time_manager
  #     mix test
