name: Main Build and Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # merge_group:
  #   types: ['checks_requested']

jobs:
  setup-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir and Phoenix
        uses: erlef/setup-beam@v1.16
        with:
          elixir-version: 1.15.7
          otp-version: 26.0
      - name: Install Backend Dependencies
        run: |
          cd api
          pwd
          mix deps.get

  backend-test:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: setup-backend

    steps:
      - name: Run Tests
        run: |
          cd api
          mix ecto.create
          mix test

  setup-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Frontend Dependencies
        run: |
          cd front
          pwd
          yarn install

  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: setup-frontend

    steps:
      - name: Run Tests
        run: |
          yarn test
